os/arch/arm: remove rtw_timer.c, rtw_wakelock.c, rtw_atomic.c from AP wifi libs
- add linker option --whole-archive so that all the symbols inside static libaries will be looked through
- during linking stage, will encounter undefined reference to pmu_yield_os_check, pmu_acquire_wakelock, pmu_release_wakelock when using linker option --whole-archive on EXTRA_LIBS, because linker will looking through all the symbols

Ref: https://github.com/Samsung/TizenRT/pull/7051